Repository StefanoBelli/telegram-bot-api, pull requests merged in 2018-03, with the labels that each got.

#21 Cmake submodule
  CMakeLists.txt
  src/CMakeLists.txt
Labels: build system, enhancement

#20 chatInfo.cpp
  examples/chatInfo.cpp
Labels: examples

#22 Callbacks using std::functions or lamdas
  include/tgbot/register_callback.h
Labels: enhancement
